WIP: FCCAnalysis chain
HEP-FCC/fcc-tutorials pull request #46
Opened 2020-08-20 12:21 UTC by clementhelsens

2020-09-16 07:12 UTC, vvolkl commented on FCCsnowmass.md
> +- **Pythia_ee_ZH_Zmumu_ecm240.cmd** for the Higgs Stralhung signal
```suggestion
- **Pythia_ee_ZH_Zmumu_ecm240.cmd** for the Higgs Strahlung signal
```

2020-09-17 13:29 UTC, vvolkl commented
For the page to show up on the website, you need to add the filename on the top level Readme: https://github.com/HEP-FCC/fcc-tutorials/blob/master/README.md

2020-09-17 13:30 UTC, vvolkl requested changes

2020-09-17 13:30 UTC, vvolkl commented on FCCsnowmass.md
> +{% endobjectives %}
I think sphinx needs  an empty line after endobjectives.

2020-09-18 07:01 UTC, clementhelsens commented on FCCsnowmass.md
> +- **Pythia_ee_ZH_Zmumu_ecm240.cmd** for the Higgs Stralhung signal
thanks

2020-09-18 07:02 UTC, clementhelsens commented on FCCsnowmass.md
> +{% endobjectives %}
ok

2020-09-18 08:11 UTC, merged